<?php
// Variables
return [
  'creatorName' => 'Mahasiswa Universitas Pamulang',
  'creatorUrl' => 'https://kedaiprogrammer.com',
  'templateName' => 'SMKN 8',
  'templateSuffix' => 'SMK Negeri 8 Kab. Tangerang',
  'templateVersion' => '1.0.1',
  'templateFree' => false,
  'templateDescription' => 'Start your development with a Dashboard for Bootstrap 5',
  'templateKeyword' => 'dashboard, bootstrap 5 dashboard, bootstrap 5 design, bootstrap 5',
  'licenseUrl' => 'https://themeforest.net/licenses/standard',
  'livePreview' => 'https://demos.pixinvent.com/vuexy-html-admin-template/landing/',
  'productPage' => 'https://1.envato.market/vuexy_admin',
  'support' => 'https://pixinvent.ticksy.com/',
  'moreThemes' => 'https://1.envato.market/pixinvent_portfolio',
  'documentation' => 'https://demos.pixinvent.com/vuexy-html-admin-template/documentation',
  'generator' => '',
  'changelog' => 'https://demos.pixinvent.com/vuexy/changelog.html',
  'repository' => 'https://github.com/pixinvent/vuexy-html-admin-template',
  'gitRepo' => 'septiyandn',
  'gitRepoAccess' => '/',
  'githubFreeUrl' => '/',
  'facebookUrl' => '#',
  'twitterUrl' => '#',
  'githubUrl' => 'https://github.com/SeptiyanDN',
  'dribbbleUrl' => '#',
  'instagramUrl' => 'https://www.instagram.com/septiyaaan/',
];
